plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'springweb'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// 의존성(dependences){ } 안에 프로젝트내 추가할 라이브러리 코드 --> 자동으로 라이브러리 설치
	// springboot
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	// mysql
  	runtimeOnly 'com.mysql:mysql-connector-j'
	// lombok
	compileOnly 'org.projectlombok:lombok'
  	annotationProcessor 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
